version: '3.8'
services:
  minecraft-server:
    container_name: minecraft-server
    image: itzg/minecraft-server:java8-multiarch  # Forge のバージョンが 1.18 未満の場合は、java8-multiarch を利用
    ports:
      - "25565:25565"
    volumes:
      - "./data:/data"
    environment:
      EULA: "TRUE"
      TYPE: "FORGE"
      VERSION: "1.12.2"
      FORGEVERSION: "RECOMMENDED"
      MEMORY: "2G"
      OVERRIDE_SERVER_PROPERTIES: "TRUE"
      MODE: creative  # クリエイティブモード
      LEVEL_TYPE: FLAT  # スーパーフラットワールド
      DIFFICULTY: peaceful  # ピースフルモード
      ALLOW_CHEATS: "true"  # チート許可
      SPAWN_MONSTERS: "false"  # 敵スポーンなし
      PVP: "false"  # PVP無効
      ONLINE_MODE: "FALSE"  # LAN内のみ利用
    restart: unless-stopped
